import z from "zod";
import { CategoriaDefinicionSchema, type CategoriasCatalogInput } from "$lib/schema/catalog/category";
import { ConvocatoriaEnum, HabilidadCombateBasicaEnum, HabilidadPsiquicaBasicaEnum, HabilidadSobrenaturalBasicaEnum } from "$lib/schema/common/enums";
import { SecundariasBaseTodasEnum, SecundariasCostePDBaseSchema } from "./secondaryAbilities";
import { schemaFromEnum, uniqueValues } from "$lib/schema/common/utils";
import { PositiveInt } from "$lib/schema/common/basic_types";


// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------
export const ArquetipoEnum = z.enum([
  "Luchador",
  "Domine",
  "Acechador",
  "Místico",
  "Psíquico",
]);

export const CategoriaBaseEnum = z.enum([
  "Guerrero",
  "Guerrero Acróbata",
  "Paladín (F)",
  "Paladín Oscuro (RD)",
  "Maestro en Armas",
  "Tecnicista",
  "Tao",
  "Explorador",
  "Sombra",
  "Ladrón",
  "Asesino",
  "Hechicero",
  "Warlock",
  "Ilusionista",
  "Hechicero Mentalista",
  "Conjurador",
  "Guerrero Conjurador",
  "Mentalista",
  "Guerrero Mentalista",
  "Novel",
]);

export const PrimariasTodasEnum = z.enum([
  ...HabilidadCombateBasicaEnum.options,
  ...HabilidadSobrenaturalBasicaEnum.options,
  ...ConvocatoriaEnum.options,
  ...HabilidadPsiquicaBasicaEnum.options,
])

// helper schema for validation
const categoriaInversionBaseSchema = CategoriaDefinicionSchema.extend({
  arquetipos:            z.array(ArquetipoEnum).refine(uniqueValues(), { message: "Arquetipo duplicado" }),
  secundarias:           SecundariasCostePDBaseSchema,
  bonificadores_innatos: z.object({
    primarias:           schemaFromEnum(PrimariasTodasEnum, PositiveInt).partial().strict().optional(),
    secundarias:         schemaFromEnum(SecundariasBaseTodasEnum, PositiveInt).partial().strict().optional(),
  }),
})

export const CategoriasInversionBaseSchema = schemaFromEnum(CategoriaBaseEnum, categoriaInversionBaseSchema)

// ---------------------------------------------------------------------------
// Default categories — official Anima: Beyond Fantasy base rules.
// ---------------------------------------------------------------------------

export const CategoriasBaseCatalog: CategoriasCatalogInput = {
  "Guerrero": {
    arquetipos:        ["Luchador"],
    turno:             5,
    pv:                15,
    coste_multiplo_pv: 15,
    limite_combate:    0.6,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2, particular: { proeza_de_fuerza: 1 } },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5, habilidad_de_parada: 5, llevar_armadura: 5 },
      secundarias: { proeza_de_fuerza: 5 },
    },
  },
  "Guerrero Acróbata": {
    arquetipos:        ["Luchador"],
    turno:             10,
    pv:                10,
    coste_multiplo_pv: 20,
    limite_combate:    0.6,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  3,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5, habilidad_de_esquiva: 5 },
      secundarias: { acrobacias: 10, saltar: 10, atletismo: 10, trucos_de_manos: 10, estilo: 10 },
    },
  },
  "Paladín (F)": {
    arquetipos:        ["Luchador"],
    turno:             5,
    pv:                15,
    coste_multiplo_pv: 15,
    limite_combate:    0.6,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2, particular: { resistir_el_dolor: 1 } },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_parada: 5, llevar_armadura: 10 },
      secundarias: { estilo: 5, liderazgo: 10, resistir_el_dolor: 10, frialdad: 10 },
    },
  },
  "Paladín Oscuro (RD)": {
    arquetipos:        ["Luchador"],
    turno:             5,
    pv:                15,
    coste_multiplo_pv: 15,
    limite_combate:    0.6,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2, particular: { frialdad: 1 } },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5, llevar_armadura: 5 },
      secundarias: { estilo: 5, intimidar: 10, frialdad: 10, persuasion: 5, resistir_el_dolor: 10 },
    },
  },
  "Maestro en Armas": {
    arquetipos:        ["Luchador"],
    turno:             5,
    pv:                20,
    coste_multiplo_pv: 10,
    limite_combate:    0.6,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   1,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5, habilidad_de_parada: 5, llevar_armadura: 10 },
      secundarias: { proeza_de_fuerza: 5 },
    },
  },
  "Tecnicista": {
    arquetipos:        ["Domine"],
    turno:             5,
    pv:                5,
    coste_multiplo_pv: 20,
    limite_combate:    0.6,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5 },
      secundarias: {  },
    },
  },
  "Tao": {
    arquetipos:        ["Domine", "Luchador"],
    turno:             5,
    pv:                10,
    coste_multiplo_pv: 20,
    limite_combate:    0.6,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   {  },
      secundarias: { estilo: 5 },
    },
  },
  "Explorador": {
    arquetipos:        ["Acechador", "Luchador"],
    turno:             5,
    pv:                10,
    coste_multiplo_pv: 20,
    limite_combate:    0.6,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 3, particular: { herbolaria: 2, animales: 1, medicina: 2 } },
      vigor: { general: 2 },
      subterfugio: { general: 2, particular: { tramperia: 1 } },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5 },
      secundarias: { advertir: 10, buscar: 10, rastrear: 10, tramperia: 5, animales: 5, herbolaria: 5 },
    },
  },
  "Sombra": {
    arquetipos:        ["Acechador", "Luchador"],
    turno:             10,
    pv:                5,
    coste_multiplo_pv: 20,
    limite_combate:    0.6,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  3,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5, habilidad_de_esquiva: 5 },
      secundarias: { advertir: 10, buscar: 10, ocultarse: 10, sigilo: 10 },
    },
  },
  "Ladrón": {
    arquetipos:        ["Acechador"],
    turno:             10,
    pv:                5,
    coste_multiplo_pv: 20,
    limite_combate:    0.5,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  3,
      habilidad_de_esquiva: 2,
      llevar_armadura:   3,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 3, particular: { tasacion: 1 } },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_esquiva: 5 },
      secundarias: { trucos_de_manos: 5, advertir: 5, buscar: 5, tramperia: 5, ocultarse: 5, sigilo: 5, robo: 10 },
    },
  },
  "Asesino": {
    arquetipos:        ["Acechador"],
    turno:             10,
    pv:                5,
    coste_multiplo_pv: 20,
    limite_combate:    0.5,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  3,
      habilidad_de_esquiva: 2,
      llevar_armadura:   3,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 3, particular: { memorizar: 2 } },
      vigor: { general: 3, particular: { frialdad: 2 } },
      subterfugio: { general: 2, particular: { sigilo: 1 } },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5 },
      secundarias: { frialdad: 10, advertir: 10, buscar: 10, tramperia: 10, ocultarse: 10, sigilo: 10, venenos: 10 },
    },
  },
  "Hechicero": {
    arquetipos:        ["Místico"],
    turno:             5,
    pv:                5,
    coste_multiplo_pv: 20,
    limite_combate:    0.5,
    limite_magia:      0.6,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  3,
      habilidad_de_parada:  3,
      habilidad_de_esquiva: 2,
      llevar_armadura:   3,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2, particular: { valoracion_magica: 1 } },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   {  },
      secundarias: { ocultismo: 5, valoracion_magica: 10 },
    },
  },
  "Warlock": {
    arquetipos:        ["Luchador", "Místico"],
    turno:             5,
    pv:                10,
    coste_multiplo_pv: 20,
    limite_combate:    0.5,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5, habilidad_de_parada: 5, habilidad_de_esquiva: 5 },
      secundarias: { valoracion_magica: 5 },
    },
  },
  "Ilusionista": {
    arquetipos:        ["Acechador", "Místico"],
    turno:             5,
    pv:                5,
    coste_multiplo_pv: 20,
    limite_combate:    0.5,
    limite_magia:      0.6,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  3,
      habilidad_de_parada:  3,
      habilidad_de_esquiva: 2,
      llevar_armadura:   3,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2, particular: { persuasion: 1 } },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2, particular: { trucos_de_manos: 1 } },
    },
    bonificadores_innatos: {
      primarias:   {  },
      secundarias: { trucos_de_manos: 10, persuasion: 5, ocultarse: 10, sigilo: 10, robo: 5, valoracion_magica: 5, disfraz: 5 },
    },
  },
  "Hechicero Mentalista": {
    arquetipos:        ["Místico", "Psíquico"],
    turno:             5,
    pv:                5,
    coste_multiplo_pv: 20,
    limite_combate:    0.5,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  3,
      habilidad_de_parada:  3,
      habilidad_de_esquiva: 2,
      llevar_armadura:   3,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   {  },
      secundarias: { ocultismo: 5, valoracion_magica: 10 },
    },
  },
  "Conjurador": {
    arquetipos:        ["Místico"],
    turno:             5,
    pv:                5,
    coste_multiplo_pv: 20,
    limite_combate:    0.5,
    limite_magia:      0.6,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  3,
      habilidad_de_parada:  3,
      habilidad_de_esquiva: 2,
      llevar_armadura:   3,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2, particular: { ocultismo: 1 } },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   {  },
      secundarias: { ocultismo: 10, valoracion_magica: 5 },
    },
  },
  "Guerrero Conjurador": {
    arquetipos:        ["Luchador", "Místico"],
    turno:             5,
    pv:                10,
    coste_multiplo_pv: 20,
    limite_combate:    0.5,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5, habilidad_de_parada: 5, habilidad_de_esquiva: 5 },
      secundarias: { ocultismo: 5 },
    },
  },
  "Mentalista": {
    arquetipos:        ["Psíquico"],
    turno:             5,
    pv:                5,
    coste_multiplo_pv: 20,
    limite_combate:    0.5,
    limite_magia:      0.5,
    limite_psi:        0.6,
    combate: {
      habilidad_de_ataque:  3,
      habilidad_de_parada:  3,
      habilidad_de_esquiva: 2,
      llevar_armadura:   3,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   {  },
      secundarias: {  },
    },
  },
  "Guerrero Mentalista": {
    arquetipos:        ["Luchador", "Psíquico"],
    turno:             5,
    pv:                10,
    coste_multiplo_pv: 20,
    limite_combate:    0.5,
    limite_magia:      0.5,
    limite_psi:        0.5,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   { habilidad_de_ataque: 5, habilidad_de_parada: 5, habilidad_de_esquiva: 5 },
      secundarias: {  },
    },
  },
  "Novel": {
    arquetipos:        [],
    turno:             5,
    pv:                5,
    coste_multiplo_pv: 20,
    limite_combate:    0.6,
    limite_magia:      0.6,
    limite_psi:        0.6,
    combate: {
      habilidad_de_ataque:  2,
      habilidad_de_parada:  2,
      habilidad_de_esquiva: 2,
      llevar_armadura:   2,
    },
    secundarias: {
      atleticas: { general: 2 },
      sociales: { general: 2 },
      perceptivas: { general: 2 },
      intelectuales: { general: 2 },
      vigor: { general: 2 },
      subterfugio: { general: 2 },
      creativas: { general: 2 },
    },
    bonificadores_innatos: {
      primarias:   {  },
      secundarias: {  },
    },
  },
} satisfies z.input<typeof CategoriasInversionBaseSchema>;
